### ISSUE TITLE
Mismatch between pssmlt results 

### ISSUE THREAD

**Issue by arpit15** [joeylitalien/drmlt-mitsuba#1]
I tried to render glass-of-water scene using files downloaded from [here](https://benedikt-bitterli.me/resources/). There seems to be a bug. Can you kindly release some files to test the implementation? The scenes links mentioned in the project README are not accessible. 

The full scene XML file is [here](https://gist.github.com/arpit15/e112baeb9c89fafe15838acde30d2d25). I used 1024spp
I used the following integrator setting for first image 
```
<integrator type="pssmlt" >
		<string name="technique" value="bdpt"/>
		<integer name="maxDepth" value="32" />
		<boolean name="strictNormals" value="true" />
	</integrator>
```
![bdpt-impl](https://user-images.githubusercontent.com/4703676/127211109-e5db6d98-db2c-48b3-a98f-4e79ef76628d.png)

I used the following integrator setting for second image
```
<integrator type="pssmlt" >
		<string name="technique" value="mmlt"/>
		<integer name="maxDepth" value="32" />
		<boolean name="strictNormals" value="true" />
	</integrator>
```
![mmlt-impl](https://user-images.githubusercontent.com/4703676/127211112-e7cc5214-7c07-4674-aa1d-b20085de6093.png)

**Comment by joeylitalien** [comment]
Hi @arpit15,

Indeed there seems to be an issue with the scene URLs; thanks for letting us know! While we address this issue, you can find the _Glass of Water_ scene [here](https://drive.google.com/file/d/1XGylgChMetVre-_vByTAJi4sFyl6cOko/view?usp=sharing). You'll notice that you need several other flags in the XML since we heavily modified the original Mitsuba integrators.

Cheers,
Joey

**Comment by arpit15** [comment]
Thanks for quick reply. I used your scene with reduced resolution. I get following images
# BDPT
![scene-bdp](https://user-images.githubusercontent.com/4703676/127225806-793750fe-c186-4f96-8c64-476fb23ef312.png)

# MMLT
![scene-mml](https://user-images.githubusercontent.com/4703676/127225860-45e16137-1a27-4fb7-9916-a29ea0754cb3.png)

There seems to be significant difference on the ice cubes and around the edges of the glass. Should I run with spp>2048 to check for convergence b/w techniques. 

Following image is obtained using original mitsuba pssmlt implementation. This image is very different from the above images. 

![scene-pssmlt-3](https://user-images.githubusercontent.com/4703676/127226115-51bd6921-5273-4d0c-ae7e-c9d676df7647.png)

**Comment by beltegeuse** [comment]
Hi @arpit15,

It seems that the difference between our implementation and the original Mitsuba one is that direct lighting is disabled in our case. 

To render direct lighting, you can change these fields to the following values:
```
<integer name="directSamples" value="-1" /> <!-- Render direct lighting with MCMC --> 
<boolean name="directSampling" value="true"/>
```

This ability to disable direct lighting is also present for the `bdpt` integrator (to produce a reference image in our case). It is common to avoid rendering direct lighting with MCMC. Instead, you can use MC to render direct lighting by setting a strictly positive integer for the `directSamples` field (not tested).

Concerning the difference with the `mmlt` technique:  I suspect that the problem comes from the inefficiency of MMLT to explore very small path-space manifolds (e.g., inter-reflections/refractions inside the ice). This problem of over exploitation vs exploration comes from two main factors:
1) Naive large step mutations in MMLT are quite inefficient. However, you can use a reversible jump approach with fully connected BDPT to increase the likelihood of sampling these very small manifolds.
2) The chain initialization we use is currently inefficient (samples uniformly distributed along with the different path depth) and increases the likelihood of not covering this type of path during the chain initialization. You can reduce this problem by increasing the `luminanceSamples` count. Again a more careful initialization by using fully connected BDPT paths will help here. 

Finally, as we do not refine the normalization for different path depths, we end up with an unbiased but inconsistent estimator :)

**Comment by arpit15** [comment]
Hey, thanks for pointing out the direct lighting parameter. I forgot about it. However, even after using those parameters, I think the image is substantially darker than mitsuba original `pssmlt` and raw `bdpt` integrator. I have also tested this scene using `tungsten` bdpt and mmlt implementation. It matches well in terms of key features highlighted in `reversible jump` paper by Bitterli et. al.

Following image using `pssmlt` integrator with `bdpt` technique 
![scene-bdp](https://user-images.githubusercontent.com/4703676/127246401-60fc629d-1844-4d81-87fc-23c822281526.png)

Following image using `pssmlt` integrator with `mmlt` technique
![scene-mml](https://user-images.githubusercontent.com/4703676/127246406-fdac29bf-958f-44cb-a992-7a8f35c60745.png)

Could kindly suggest other scenes or parameters which allow verifying scenes with other integrators originally in mitsuba?

**Comment by beltegeuse** [comment]
Thanks for your additional investigation. Can you post your images produced by `tungsten` here? I am just curious to see the difference :) I can also observe differences in terms of brightness when comparing PSSMLT+BDPT vs. MMLT (inside our implementation). But it is difficult to say if this visual artifact is due to lack of convergence/bad local exploration/inconsistent initialization or a bug.

When generating these images as above, do you used the same number of seed paths (`luminanceSamples`)? Did you try to change `luminanceSamples` to very high values (like `10000000`)? Does it reduced the issue?

Concerning other scenes, you can check the Veach door scene (http://beltegeuse.s3-website-ap-northeast-1.amazonaws.com/research/2020_DRMLT/scenes/veach-door_mmlt.zip) and check if the glass teapot looks correct or not. You can try scenes with simpler light transport as well, like "the hazy staircase."

If there is a bug, I will bet that it is due to wrong computations involving dielectric material (transmission events). 

However, I am not very surprised about the darkening issue with MMLT for this particular scene. Indeed, in this scene, the contributive light path has many geometrical constraints, which are difficult to explore with single sampling strategies. This darkening issue is also visible for this scene in Fig 6 of the RJMLT paper. PSSMLT BDPT/Path constructs multiple paths at once (for a given Markov state), which regularises the target function making it easier to have an efficient global exploration strategy.

**Comment by arpit15** [comment]
I used the `luminanceSamples=100
![scene](https://user-images.githubusercontent.com/4703676/127338431-ff6983b4-041a-4bb1-a0e9-bb9bef39e6e1.png)
000` for the original mitsuba PSSMLT + BDPT image posted above.
Images with `luminanceSamples=100000` using tungsten PSSMLT + BDPT
![TungstenRender](https://user-images.githubusercontent.com/4703676/127334722-6a112102-558f-4d31-9666-549fdf232075.png)

Images with `luminanceSamples=100000` using tungsten MMLT. Increasing luminanceSamples doesn't increase image brightness in tungsten for this case.
 
![TungstenRender](https://user-images.githubusercontent.com/4703676/127334918-34b75db2-8c8c-4606-89cb-9f26f759223c.png)

Images with `luminanceSamples=1000000` using DRMLT.
PSSMLT + BDPT
![scene-bdp](https://user-images.githubusercontent.com/4703676/127342133-7749fbc2-b93e-47ad-abc7-2f94ed6d7061.png)
PSSMLT + MMLT
![scene-mml](https://user-images.githubusercontent.com/4703676/127342155-6fefd834-6d65-49f9-b01a-25ab1af855d5.png)

 

The AWS link is still not reachable for me. I am unaware of the hazy staircase scene. Can you kindly refer me to it? I want to make sure I use the correct parameter to run with your implementation. 

Utah Teapot scene from [here](https://benedikt-bitterli.me/resources/) with `sigmaA=0.1486`(DRMLT supports 
Tungsten MMLT 
![teapot-full](https://user-images.githubusercontent.com/4703676/127342031-52f9bacc-e7ab-4449-9ee8-292685dad568.png)

Tungsten PSSMLT
![teapot-full](https://user-images.githubusercontent.com/4703676/127341736-bf0d757a-5098-4bba-9c93-931c32a3e95b.png)


Mitsuba PSSMLT + PATH
![scene-pssmlt-path](https://user-images.githubusercontent.com/4703676/127340924-00c0036a-faef-4d4c-a58b-a41a7622d897.png)

DRMLT PSSMLT + PATH
![scene-drmlt-pssmlt-path](https://user-images.githubusercontent.com/4703676/127340383-813808c6-a12a-459d-870b-29c394236cd2.png)

**Comment by beltegeuse** [comment]
Sorry but I start to have trouble understanding your problem: Does it related to DRMLT specifically or MMLT in general?

Because I can observe the darkening issue between tungsten PSSMLT vs. tungsten MMLT (images you provided). Again, as I said already above, this darkening is certainly due to bad global exploration, affecting the brightness level in large image regions. 

Concerning the last image sent (DRMLT + PSSMLT with path), the image has the wrong scaling factor (wrong image exposition?) at least. You can try to change the number of seed paths or increase pLarge to see if it does not "fix" the problem. 

For the AWS links: Please copy-paste them inside your web browser. You cannot directly click on the link due to a new security feature on Github. The link provided earlier is functional. 

For the Hazy staircase: Please look at the DRMLT paper. It is the Wooden Staircase with infinite homogeneous participating media. Unfortunately, I did not have access to the scene right now.

**Comment by arpit15** [comment]
Since repository has substantial changes along with new additions, I am trying to check if the old algorithms in Mitsuba match with this repository. My understanding is that PSSMLT + PATH and PSSMLT + BDPT in DRMLT(this repo) should match with the original Mitsuba PSSMLT + bidirectional=false and PSSMLT + bidirectional=true. Can you kindly let me know if this is a wrong assumption?

In the past, when I have run tungsten MMLT to convergence, I have been able to match it to tungsten  PSSMLT or BDPT. That's why I am unsure of why there is substantial brightness variation for the scenes.  

I am able to download the scenes. Thanks.

**Comment by beltegeuse** [comment]
>  Can you kindly let me know if this is a wrong assumption?

No it is a good assumption that the code inside the same rendering system should match. But it is not guarentee that images matches between different rendering system (e.g., tungsten). Note also that some algorithm differences will generate different image artifact at the end. 

Below images generated from Mitsuba and our code base. I can see small differences on some part of the image:
- One black cracks is visible on Mitsuba images. This might be due to differences on how local frame are computed. 
- Some small highlight are also visible inside Mitsuba. 

But all the different images looks quite the same to me. 

Reference (BDPT, generated with ours code base):
![reference](https://user-images.githubusercontent.com/339446/127392356-8ddcc1bf-be0f-4f83-ad11-7f2fdc09b5fc.png)

Mitsuba PSSMLT (Path):
![mitsuba_pssmlt_path](https://user-images.githubusercontent.com/339446/127392405-bae1b8be-9ca7-45e2-9e70-1a61a1d63a8d.png)

Mitsuba PSSMLT (BDPT):
![mitsuba_pssmlt_bdpt](https://user-images.githubusercontent.com/339446/127392449-8041d766-0205-4f73-a52f-b975e5a45692.png)

Ours PSSMLT (Path):
![ours_pssmlt_path](https://user-images.githubusercontent.com/339446/127392489-3df7488b-ad53-4486-8251-05a12cb9f177.png)

Ours PSSMLT (BDPT):
![ours_pssmlt_bdpt](https://user-images.githubusercontent.com/339446/127392575-9c700efa-d3e6-4e3c-866c-26f95ca8a03a.png)

**Comment by beltegeuse** [comment]
Note that these images are not equal-time or equal-spp images. PSSMLT with BDPT is quite slow as samples are more costly to evaluate.

**Comment by arpit15** [comment]
Thanks for taking the time to post images to compare Mitsuba and your implementation. I am currently not concerned with the speed. I am just trying to verify that the images converge to the same solution. 
For some weird reason, the rendered image on my end with `drmlt` PSSMLT + BDPT (`spp=2048`) is darker around the glass. I am generating HDR images and then dumping png using [tev](https://github.com/Tom94/tev) without gamma correction. Therefore, I expect the brightness to match with your image and Mitsuba PSSMLT + BDPT
![scene-bdp](https://user-images.githubusercontent.com/4703676/127405327-6fc613ce-adbe-4f57-afbb-68190378ca42.png)

I used following parameters 
```
<default name="integrator" value="pssmlt"/>
	<default name="kelemenStyleMutation" value="true"/>
	<default name="pLarge" value="0.3"/>
	<default name="type" value="mirasym"/>
	<default name="sigma" value="0.015625"/>
	<default name="useMixture" value="false" />
	<default name="stageRatio" value="0.5" />
        <default name="acceptanceMap" value="false" />
        <default name="fixEmitterPath" value="false" />
	<default name="optimizedTracing" value="false" />
	
	<integrator type="$integrator" >
		<integer name="maxDepth" value="33" />
		<integer name="rrDepth" value="18" />
		<integer name="directSamples" value="-1" />
		<integer name="luminanceSamples" value="10000000" />
		<boolean name="bidirectional" value="true" />
		<boolean name="directSampling" value="true"/>
		<boolean name="kelemenStyleWeights" value="true" />
		<boolean name="strictNormals" value="true" />
		<string name="technique" value="bdpt" />
		<float name="pLarge" value="$pLarge" />
		<boolean name="kelemenStyleMutation" value="$kelemenStyleMutation" />
		<string name="type" value="$type" />
		<float name="sigma" value="$sigma" />
		<boolean name="acceptanceMap" value="$acceptanceMap" />
		<boolean name="fixEmitterPath" value="$fixEmitterPath" />
		<boolean name="optimizedTracing" value="$optimizedTracing" />
		<boolean name="useMixture" value="$useMixture" />
		<float name="stageRatio" value="$stageRatio" />

		<float name="averageLuminance" value="0.09119507" />
	</integrator>
```

Can you kindly post the parameters you used to generate the last image in [your](https://github.com/joeylitalien/drmlt-mitsuba/issues/1#issuecomment-888608521) post?

**Comment by beltegeuse** [comment]
These are the parameters that I used:
```<scene version="0.5.0" >
	<default name="integrator" value="path"/>
	<default name="kelemenStyleMutation" value="true"/>
	<default name="pLarge" value="0.3"/>
	<default name="type" value="mirasym"/>
	<default name="sigma" value="0.015625"/>
	<default name="useMixture" value="false" />
	<default name="stageRatio" value="0.5" />
	<default name="acceptanceMap" value="false" />
        <default name="fixEmitterPath" value="false" />
	<default name="optimizedTracing" value="false" />
	<default name="technique" value="path" />
	<default name="luminanceSamples" value="100000" /> 
	<integrator type="$integrator" >
		<integer name="maxDepth" value="17" />
		<integer name="rrDepth" value="18" />
		<integer name="directSamples" value="0" />
		<integer name="luminanceSamples" value="$luminanceSamples" />
		<boolean name="bidirectional" value="false" />
		<boolean name="directSampling" value="false"/>
		<boolean name="kelemenStyleWeights" value="true" />
		<boolean name="strictNormals" value="true" />
		<string name="technique" value="$technique" />
		<float name="pLarge" value="$pLarge" />
		<boolean name="kelemenStyleMutation" value="$kelemenStyleMutation" />
		<string name="type" value="$type" />
		<float name="sigma" value="$sigma" />
		<boolean name="acceptanceMap" value="$acceptanceMap" />
		<boolean name="fixEmitterPath" value="$fixEmitterPath" />
		<boolean name="optimizedTracing" value="$optimizedTracing" />
		<boolean name="useMixture" value="$useMixture" />
		<float name="stageRatio" value="$stageRatio" />

		<float name="averageLuminance" value="0.09119507" />
	</integrator>
       <!-- ... -->
```

Then I have called `mitsuba` with:
```bash
./mitsuba <path_scene>/scene.xml -r 10  -D integrator=pssmlt -D luminanceSamples=1000000 -D technique=bdpt -o ours_pssmlt_bdpt
./mitsuba <path_scene>/scene.xml -r 10  -D integrator=pssmlt -D luminanceSamples=1000000 -D technique=path -o ours_pssmlt_path
````

Note that these images produced above are with `PSSMLT` and not `DRMLT`. I did not check what `DRMLT` gives as your last questions was regarding PSSMLT. Also, it is easier to use the same rendering algorithm to spot differences between this code base and original code base. 

Regarding the configuration, you put just above:
- Russian roulette should be desactived for MMLT (`rrDepth` > `maxDepth`).
- You changed the maxDepth (from 17 to 18) but did not put `averageLuminance` to `-1`. This means that the image that you compute do not have the correct normalization factor (= global brightness). 
- Direct sampling is desactived in all tests shown inside the paper. If you activate direct lighting (`directSamples` set to `-1`), you should put `averageLuminance` to -1 or recompute the correct value. 
- `kelemenStyleWeights` cannot be used with `DRMLT` integrator (just to make sure you know about it)

**Comment by beltegeuse** [comment]
I will close with this issue for the moment. Please free to re-open it if you found any problem on DRMLT or code base. Good luck!

**Comment by arpit15** [comment]
@beltegeuse  Thanks for your time. I recompiled and verified the scenes provided in your repo(plus `teapot-full` scenes from Benedikt) with `pssmlt` + `bdpt` against Mitsuba with and without `averageLuminance`. Everything seems to match as expected. 

Can you kindly clarify your last comment on [this](https://github.com/joeylitalien/drmlt-mitsuba/issues/1#issuecomment-887885469) post?
`Finally, as we do not refine the normalization for different path depths, we end up with an unbiased but inconsistent estimator`

**Comment by beltegeuse** [comment]
You can look at the document provided by Prof. Hachisuka on bias/consistency:
"Five Common Misconceptions about Bias in Light Transport Simulation"
https://cs.uwaterloo.ca/~thachisu/misc.pdf

But an unbiased but inconsistent estimator means that:
- unbiased: If you average several independent runs (including computing the normalization factor), this will converge to the correct result
- inconsistent: one infinite long run does not converge to the correct results as the error inside the normalization factor does not get reduced over time. 

To make the estimator consistent, you should also refine the normalization factor when you take more samples. In our case, it was not a problem, as we precompute the normalization factor and make sure that it corresponds to the reference value (by properly setting `averageLuminance`).

**Comment by arpit15** [comment]
Thanks for the reference and for providing definitions in this context.
